version: "3"
services:
  generator:
    build: .
    ports:
      - 8082:8082
    volumes:
      - ./qr_public.pem:/app/qr_public.pem
    environment:
      - PostgresPort=5432
      - PostgresHost=10.10.176.12
      - PostgresDBName=postgres
      - PostgresUser=ADMIN
      - PostgresPassword=admin_pass
      - RSAPublicKey=/app/qr_public.pem
      - Port=8082
      - RedisAddress=10.10.176.12:6379
      - RedisDB=0