version: '3'

services:
  postgres:
    image: postgres:15.1
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin_pass
      POSTGRES_USER: ADMIN
  redis:
    image: redis:7.0.7
    restart: always
    ports:
      - 6379:6379  
