version: '3.1'

services:
  postgres:
    restart: always
    image: postgres:15.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin_pass
      POSTGRES_USER: ADMIN
  redis:
    restart: always
    image: redis/redis-stack:6.2.6-v6
    ports:
      - 6379:6379  
      - 8001:8001