version: "3.8"
services:
  app:
    build: .
    restart: always
    ports:
      - "9095:80"
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost" ]
      interval: 1m30s
      timeout: 10s
      retries: 3