FROM mcr.microsoft.com/dotnet/sdk:7.0 as build-env
WORKDIR /build
COPY . .
RUN dotnet restore

RUN dotnet publish /build/src/QR.Client.DbMigrator/QR.Client.DbMigrator.csproj -c Release -o /DbMigrator

FROM mcr.microsoft.com/dotnet/aspnet:7.0 as runtime
WORKDIR /publish
COPY --from=build-env /DbMigrator .

ENTRYPOINT ["dotnet", "QR.Client.DbMigrator.dll"]