version: "3"
services:
  decrypt:
    build: .
    ports:
      - 8083:8083
    volumes:
      - ./qr_private.key:/app/qr_private.key
    environment:
      - PostgresPort=5432
      - PostgresHost=10.0.0.112
      - PostgresDBName=postgres
      - PostgresUser=ADMIN
      - PostgresPassword=admin_pass
      - RSAPrivateKey=/app/qr_private.key
      - Port=8083
      - QRDecoder=http://10.0.0.112:8080/qr/GetQrCode