version: "3"
services:
  decrypt:
    build: .
    restart: always
    ports:
      - 8083:8083
    volumes:
      - ./qr_private.key:/app/qr_private.key
    environment:
      - PostgresPort=5432
      - PostgresHost=10.0.0.4
      - PostgresDBName=postgres
      - PostgresUser=ADMIN
      - PostgresPassword=admin_pass
      - RSAPublicKey=./qr_public.pem
      - RSAPrivateKey=./qr_private.key
      - Port=8083
      - QRDecoder=https://crypter.adizes.com.br/scanner/GetQrCode
      - RedisAddress=10.0.0.4:6379
      - RedisDB=0